services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_USER_PASS
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - memorizer_volume:/var/lib/mysql
    networks:
      - memorizer_network

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - memorizer_network

networks:
  memorizer_network:
    ipam:
      driver: default

volumes:
  memorizer_volume:
